blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/marijnbent/obsidian-print/discussions/new?category=ideas
    about: Please submit feature requests as discussions. This allows for better engagement and feedback.
  - name: â“ Question
    url: https://github.com/marijnbent/obsidian-print/discussions/new?category=q-a
    about: Please ask questions in discussions.